
export interface Technology {
  name: string;
  location?: string;
  productName?: string;
  quality: 'Proven' | 'Emerging' | 'Experimental';
  description: string;
  website: string;
  contact?: string;
  ratedPower?: string;
  efficiency?: string;
  costNotes?: string;
  sources?: string;
}

export interface PortfolioCategory {
  category: string;
  technologies: Technology[];
}

export const PORTFOLIO_DATA: PortfolioCategory[] = [
  {
    category: 'Wind Generators and Turbines',
    technologies: [
      {
        name: 'SkySails Power',
        location: 'Hamburg, Germany',
        productName: 'Kyo Airborne Wind System',
        quality: 'Emerging',
        description: 'An automatically controlled massive kite that harnesses energy using a "yo-yo principle" and a figure 8 pattern. The energy can be fed to the grid, stored, or directly consumed.',
        website: 'https://skysails-power.com/',
        contact: 'power@skysails.de or +49 (0)40-702990',
        ratedPower: 'Up to 450 kW, ~1,780 MWh/yr per system',
        efficiency: 'Operates up to ~750 m altitude; figure-8 traction cycles',
        costNotes: 'Utility/commercial scale; Request quote',
        sources: '(SkySails-Power)',
      },
      {
        name: 'KitePower',
        location: 'Delft, The Netherlands',
        productName: 'Falcon',
        quality: 'Emerging',
        description: 'A mobile wind energy solution that is easy to transport and install, requiring minimal ground space. It can be integrated into existing microgrids.',
        website: 'https://thekitepower.com/contact/',
        contact: 'See website contact form.',
        ratedPower: '100 kW nominal; power curves published',
        efficiency: '24/7 renewable (night, cloudy); GS lifetime 25 yrs',
        costNotes: 'Mobile / microgrid; Request quote',
        sources: '(Kitepower)',
      },
      {
        name: 'Oy Windside Production Ltd',
        location: 'Viitasaari, Finland',
        productName: 'WS-30',
        quality: 'Proven',
        description: 'Produces residential and commercial vertical wind turbines. The WS-30 model is targeted to feed energy to the grid.',
        website: 'https://windside.com/products/ws-30/',
        contact: 'general@windside.com or +358-207-304-360',
        ratedPower: 'Model aimed at grid-feed; (maker does not publish a fixed kW on page)',
        efficiency: 'VAWT for harsh sites',
        costNotes: 'Request quote',
        sources: '(product page offers form; no fixed kW listed)',
      },
      {
        name: 'BE-WIND LLC',
        location: 'Merritt Island, FL, USA',
        quality: 'Proven',
        description: 'A hybrid quad solar panel energy system (up to 5KW). It\'s a direct ground mount that uses 85% less space than a comparable solar system and can be used for standalone microgrids.',
        website: 'http://be-wind.com/turbines',
        contact: 'mberdan@be-wind.com or 214-649-4862',
        ratedPower: 'Up to ~5 kW (system)',
        efficiency: '85% less footprint vs comparable PV (claim)',
        costNotes: 'Request quote',
        sources: '(company product page; no full datasheet public)',
      },
      {
        name: 'The Power Collective',
        location: 'Kingston, ON, Canada',
        productName: 'Ridgeblade RB1 / RB2',
        quality: 'Proven',
        description: 'Offers the RB1 Residential (compact, quiet turbine) and the RB2 Commercial (modular, high output) wind turbines, as well as hybrid solar units.',
        website: 'https://ridgeblade.com/',
        contact: 'info@thepowercollective.ca or (+1) 613-766-1687',
        ratedPower: 'Residential RB1 / commercial RB2 (modular)',
        efficiency: 'Quiet, building-integrated',
        costNotes: 'Request quote',
        sources: '(site provides contact; detailed kW via proposal)',
      },
      {
        name: 'SD Wind',
        location: 'Odessa, Texas, USA',
        productName: 'SD6 / SD6+',
        quality: 'Proven',
        description: 'Horizontal wind turbines.',
        website: 'https://sd-windenergy.com/small-wind-turbines/',
        contact: '001 817 723 6338 (Brian Fawcett)',
        ratedPower: '5.2–6 kW rated (peaks to ~9 kW in high winds)',
        efficiency: '5.6 m rotor; class-1; grid-tie or battery',
        costNotes: 'Small wind; Request quote',
        sources: '(SD Wind Energy)',
      },
    ],
  },
  {
    category: 'Hydro-Electric Generators',
    technologies: [
      {
        name: 'Natel Energy, Inc',
        location: 'Alameda, CA, USA',
        productName: 'Restoration Hydro Turbine (RHT)',
        quality: 'Proven',
        description: 'A fish-safe (99% survival) Restoration Hydro Turbine with >90% efficiency. It offers generating capacities from 30 kW to over 3 MW and can be used for new projects or retrofitting existing dams.',
        website: 'https://www.natelenergy.com/',
        contact: 'info@natelenergy.com or 510.342.5269',
        ratedPower: '30 kW → 3+ MW project range',
        efficiency: '>90% hydraulic efficiency, >99% fish survival',
        costNotes: 'Project EPC; Request quote',
        sources: '(Factor This™)',
      },
      {
        name: 'In-pipe energy',
        location: 'Portland, Oregon, USA',
        productName: 'In-PRV®',
        quality: 'Proven',
        description: 'The In-PRV® system is installed alongside a Pressure Reducing Valve (PRV) in a water utility bypass, converting wasted pressure into energy for operations or sale to the grid.',
        website: 'https://www.inpipeenergy.com/',
        contact: 'info@inpipeenergy.com or 310-906-0783',
        ratedPower: 'Case: Hillsboro OR ~185 MWh/yr (published)',
        efficiency: 'Harvests pressure energy; continuous',
        costNotes: 'Utility PPA/onsite; Request quote',
        sources: '(Taylor & Francis Online)',
      },
      {
        name: 'Turbulent',
        location: 'Belgium',
        quality: 'Proven',
        description: 'Resilient, cost-efficient hydroelectric turbines (15 to 70 kW) to power businesses and communities. Can be clustered to create multi-megawatt projects.',
        website: 'https://www.turbulent.be/',
        contact: 'See website "Get Started" page for partner network.',
        ratedPower: '15–70 kW per turbine',
        efficiency: '~60% total efficiency; can cluster',
        costNotes: 'Request quote',
        sources: '(Engineering For Change)',
      },
      {
        name: 'New England Hydropower',
        location: 'Beverly, MA, USA',
        productName: 'Archimedes Screw Turbine (AST)',
        quality: 'Proven',
        description: 'Deploys modern Archimedes Screw Turbines (ASTs) on existing dams and canals. They evaluate, permit, engineer, build, and often own the operation, selling the power.',
        website: 'https://www.nehydropower.com/technology',
        contact: 'roger@NEHydropower.com or (1) 860 729 9767',
        ratedPower: 'Site-specific (typically 10s–100s kW per screw)',
        efficiency: 'Fish-friendly, low-head',
        costNotes: 'Developer/owner-operator; Request quote',
        sources: '(solarimpulse.com)',
      },
    ],
  },
  {
    category: 'Solar Technology',
    technologies: [
      {
        name: 'Heliene',
        location: 'Sault Ste. Marie, Ontario, Canada',
        productName: '72M Module',
        quality: 'Proven',
        description: 'Solar panels.',
        website: 'https://heliene.com/products/',
        contact: '+1 705-575-6556',
        ratedPower: '~340 W (example 72M-340)',
        efficiency: '~17.8%; std warranties',
        costNotes: 'Module pricing varies; Request quote',
        sources: '(A1 SolarStore)',
      },
      {
        name: 'Silfab Solar',
        location: 'Bellingham, WA, USA',
        productName: 'SIL-420 HC',
        quality: 'Proven',
        description: 'Solar panels.',
        website: 'https://silfabsolar.com/our-solar-panels/',
        contact: '800 Cornwall Ave, Bellingham, WA 98225 USA',
        ratedPower: '420 W',
        efficiency: '21.2%; −0.36%/°C Pmax',
        costNotes: 'Street prices via distributors',
        sources: '(EnergySage)',
      },
      {
        name: 'Q Cells',
        location: 'Dalton, Georgia, USA',
        productName: 'Q.PEAK DUO BLK ML-G10+',
        quality: 'Proven',
        description: 'Solar panels.',
        website: 'https://qcells.com/us/',
        contact: 'Dalton, Georgia',
        ratedPower: '385–410 W',
        efficiency: '25-yr product & performance warranties',
        costNotes: 'Widely available; price by installer',
        sources: '(Qcells North America)',
      },
      {
        name: 'LG Solar',
        location: 'Huntsville, Alabama, USA',
        quality: 'Proven',
        description: 'Solar panels. Note: LG exited the solar panel manufacturing business in 2022, but warranties for existing products are still honored.',
        website: 'https://www.lg.com/us/solar',
        contact: 'Huntsville, Alabama',
        costNotes: 'Use channel inventory only',
        sources: '(LG IN)',
      },
      {
        name: 'Renogy',
        location: 'Ontario, California, USA',
        productName: '200W 12V Panel',
        quality: 'Proven',
        description: 'Solar panels and battery systems.',
        website: 'https://renogy.com/',
        contact: '5050 S Archibald Ave, Ontario, CA 91762',
        ratedPower: '200 W',
        efficiency: '~1 kWh/day at 5–6 sun-hrs',
        costNotes: 'Retail web pricing',
        sources: '(renogy.com)',
      },
      {
        name: 'Solar Carport Structures',
        location: 'Oxford, MI, USA',
        quality: 'Proven',
        description: 'A complete line of steel carports specifically designed for solar energy applications.',
        website: 'https://www.carportstructures.com/solar-carports',
        contact: '1-248-628-5571',
        ratedPower: 'Racking/structures',
        efficiency: '16-ga pre-punched steel; fixed tilt',
        costNotes: 'Structure pricing by span; Request quote',
        sources: '(Carport Structures Corp.)',
      },
      {
        name: 'Solar Roadways, Inc.',
        location: 'Sandpoint, ID, USA',
        productName: 'SR4 / SR5',
        quality: 'Emerging',
        description: 'Hexagonal, 48-watt solar panels designed for parking lots, sidewalks, driveways, bike paths, etc.',
        website: 'https://solarroadways.com/specifics/solar/',
        contact: 'See website "Contact" page.',
        ratedPower: 'SR4 ~48 W/panel',
        efficiency: 'Integrated heat, LEDs, comms',
        costNotes: 'Pilot/commercializing SR5; Request quote',
        sources: '(Solar Roadways)',
      },
      {
        name: 'Patio Solar',
        location: 'Budapest, Hungary',
        productName: 'PLATIO solar paver',
        quality: 'Emerging',
        description: 'PLATIO solar paver, a walkable, anti-slip, heavy-duty glass building material for areas where conventional solar cannot be deployed. The product is 95% recyclable.',
        website: 'https://platiosolar.com/',
        contact: 'info@platio.cc or +36703914708',
        ratedPower: 'Tile/paver outputs per m² (datasheet)',
        efficiency: 'Heavy-duty glass; recycled base',
        costNotes: 'Request quote',
        sources: '(BENGsolar)',
      },
      {
        name: 'Brite',
        location: 'Thessaloniki – Thermi, Greece',
        productName: 'Solar Glass',
        quality: 'Emerging',
        description: 'Agrivoltaics (transparent solar tiles for growing shade plants) and Dynamic Glass (a transparent transition lens solar panel that goes over existing glass).',
        website: 'https://www.britesolar.com/technology/brite-solar-glass/',
        contact: 'info@britesolar.com or (+30) 2310-321342',
        ratedPower: 'Transparent PV glazing',
        efficiency: 'Specs vary by product line',
        costNotes: 'Request quote',
        sources: '(tech page; project-specific)',
      },
    ],
  },
  {
    category: 'Battery Technologies',
    technologies: [
      {
        name: 'StorEn Technologies Inc.',
        location: 'Greenville, SC, USA',
        productName: '30 kWh VFB',
        quality: 'Proven',
        description: 'Residential vanadium flow battery for home storage.',
        website: 'https://www.storen.tech/residential',
        contact: 'info@storen.tech or (631) 686 4009',
        ratedPower: '5 kW / 30 kWh (stackable)',
        efficiency: 'Long life; non-flammable',
        costNotes: 'Request quote',
        sources: '(StorEn New)',
      },
      {
        name: 'SalGenX',
        location: 'Chicago Time Zone, USA',
        quality: 'Emerging',
        description: 'Commercial and residential saltwater flow battery producers. They can use salt water pools among other solutions.',
        website: 'https://salgenx.com/salgenx-saltwater-flow-battery-products.html',
        contact: 'greg@salgenx.com or +1 608-238-6001',
        costNotes: 'Request quote / due diligence',
        sources: '(salgenx.com)',
      },
      {
        name: 'Solid Power™',
        location: 'Louisville, CO, USA',
        quality: 'Emerging',
        description: 'Developer of solid-state batteries, including Silicon EV Cells, Lithium Metal cells, and Conversion Reaction Cells.',
        website: 'https://solidpowerbattery.com/',
        contact: 'See website "Contact" page.',
        ratedPower: 'All-solid-state (cells)',
        efficiency: 'Cell targets up to ~440 Wh/kg, >1,000 cycles',
        costNotes: 'For pack makers; N/A module cost',
        sources: '(solidpowerbattery.com)',
      },
      {
        name: 'Ares™',
        location: 'Denver, CO, USA',
        productName: 'Advanced Rail Energy Storage',
        quality: 'Experimental',
        description: 'Advanced Rail Energy Storage (ARES) uses rail technology and gravity for utility-scale storage. Electric motors drive mass cars uphill to store energy, which are then deployed downhill to generate power.',
        website: 'https://aresnorthamerica.com/',
        contact: 'info@aresnorthamerica.com',
        ratedPower: 'Site MW-scale',
        efficiency: '~78–84% round-trip (docs)',
        costNotes: 'Request quote',
        sources: '(California Energy Commission e-Filing)',
      },
      {
        name: 'ViZn Energy Systems',
        location: 'Columbia Falls, MT, USA',
        productName: 'GS200',
        quality: 'Proven',
        description: 'Commercial flow battery.',
        website: 'https://www.viznenergy.com/product-gs200/',
        contact: '(406) 755-9462',
        ratedPower: 'Modular, multi-hour',
        efficiency: 'Non-flammable; 20-yr life (datasheets)',
        costNotes: 'Company reorg history; Request quote',
        sources: '(Scribd)',
      },
      {
        name: 'ESS Inc',
        location: 'Wilsonville, OR, USA',
        productName: 'Energy Warehouse',
        quality: 'Proven',
        description: 'Large-scale, long-duration iron flow battery. It is water-based, non-toxic, recyclable, and has no fire risk or capacity fade.',
        website: 'https://essinc.com/',
        contact: '(855) 423-9920',
        ratedPower: 'Up to 600 kWh per unit; 4–12 h',
        efficiency: 'Unlimited cycling; water-based',
        costNotes: 'Utility/commercial; Request quote',
        sources: '(ESS Tech, Inc.)',
      },
      {
        name: 'Primus Power',
        location: 'Santa Clara, CA, USA',
        productName: 'EnergyPod 2',
        quality: 'Proven',
        description: 'Commercial flow battery (EnergyPod).',
        website: 'https://primuspower.com/en/',
        contact: 'info@primuspower.com',
        ratedPower: '25 kW / 125 kWh (5 h)',
        efficiency: '~70% DC RTE (incl. aux)',
        costNotes: 'Company status varies; Request quote',
        sources: '(primuspower.com)',
      },
      {
        name: 'Energy Vault',
        location: 'Westlake Village, CA, USA',
        productName: 'EVx',
        quality: 'Emerging',
        description: 'A building with electronic motors that lift and descend concrete blocks for energy storage; a gravity-powered battery.',
        website: 'https://www.energyvault.com/',
        contact: 'See website "Contact" page.',
        ratedPower: 'Projects: 18 MW / 36 MWh class',
        efficiency: '~75–80% round-trip (pilot to proj.)',
        costNotes: 'EPC/project; Request quote',
        sources: '(Energy Storage)',
      },
      {
        name: 'Gravitricity',
        location: 'London, UK',
        quality: 'Experimental',
        description: 'Uses weight configurations (up to 12,000 tonnes) in a deep shaft, suspended by cables and winches. Electricity is stored by raising the weights and generated by lowering them.',
        website: 'https://gravitricity.com/technology/',
        contact: 'info@gravitricity.com or +44 131 554 6966',
        ratedPower: 'Demo scale; up to multi-MW planned',
        efficiency: '50-yr+ asset potential',
        costNotes: 'Request quote',
        sources: '(tech page)',
      },
      {
        name: 'Gravity Power',
        location: 'Santa Barbara, CA, USA',
        quality: 'Experimental',
        description: 'A city-scale, gravity-powered underground piston battery. A pump/turbine forces water into a deep shaft, lifting a giant piston. As the piston drops, it forces water back through the turbine to generate electricity.',
        website: 'https://www.gravitypower.net/',
        contact: 'info@gravitypower.net or +1 925 785 8825',
        ratedPower: 'Concept/prototype',
        efficiency: 'Site-engineered',
        costNotes: 'Request quote',
        sources: '(tech pages)',
      },
      {
        name: 'Heindle Energy',
        location: 'Hamburg, Germany',
        quality: 'Experimental',
        description: 'A giant (city-size) gravity-powered underground piston battery, similar in concept to Gravity Power.',
        website: 'https://heindl-energy.com/',
        contact: 'info@heindl-energy.com',
        ratedPower: 'Concept/prototype',
        efficiency: 'Site-engineered',
        costNotes: 'Request quote',
        sources: '(tech pages)',
      },
      {
        name: 'Pumped Hydro storage (GE)',
        location: 'USA',
        quality: 'Proven',
        description: 'City reservoir energy production and storage, requiring a second reservoir at a lower altitude.',
        website: 'https://www.ge.com/renewableenergy/hydro-power/hydro-pumped-storage',
        contact: 'See website "Contact Us" page.',
      },
    ],
  },
  {
    category: 'Bioenergy - Anaerobic Digesters',
    technologies: [
      {
        name: 'Bio Energy Devco',
        location: 'Annapolis, MD, USA',
        productName: 'Maryland Bioenergy Center',
        quality: 'Proven',
        description: 'Anaerobic Digestion for cities and towns. Helps municipalities recycle organics, provides renewable natural gas (RNG), and creates organic, pathogen-free soil products.',
        website: 'https://bioenergydevco.com/',
        contact: '(443)-782-3427 or see "Contact" page.',
        ratedPower: '~110–120k tons/yr; ~312–340k MMBtu/yr RNG; 16,575 t soil amendments',
        efficiency: 'Powers ~7,600 homes/yr (equiv.)',
        costNotes: 'Tipping + RNG revenue; EPC',
        sources: '(3Degrees)',
      },
      {
        name: 'SEaB Energy Inc',
        location: 'New York, NY, USA',
        productName: 'Flexibuster™ & Muckbuster®',
        quality: 'Proven',
        description: 'Offers the Flexibuster™ (small scale, 500-2500kg/day, turns food waste into energy) and Muckbuster® (turns farm waste/manure into power) for communities and resorts.',
        website: 'http://seabenergy.com/products/',
        contact: '+202 599 4003 or see "Contact" page.',
        ratedPower: '~500–2,500 kg/day; example 600 kg/d ≈ ~80 MWh/yr elec',
        efficiency: 'CHP heat + power; modular',
        costNotes: 'Request quote',
        sources: '(SEAB Energy)',
      },
    ],
  },
  {
    category: 'Renewable Farming',
    technologies: [
      {
        name: 'AeroFarms',
        location: 'Newark, NJ, USA',
        quality: 'Proven',
        description: 'A vertical farming company that uses data science and AI to grow plants with specific, trademarked flavor profiles (FlavorSpectrum™). Uses aeroponics.',
        website: 'https://aerofarms.com/',
        contact: 'See website Partner Code of Conduct.',
        ratedPower: 'Benchmark range: ~6–18 kWh/kg for optimized lettuce systems.',
        efficiency: '"95% less water" than field.',
        costNotes: 'Ask vendor for site-specific EUI; aeroponics typically sits at the low end of VF water use.',
        sources: '(ScienceDirect, mbacasecomp.com)',
      },
      {
        name: 'Bowery Farming',
        location: 'New York, USA',
        quality: 'Proven',
        description: 'Vertical farming company that supplies greens and berries to communities and stores. Uses hydroponics.',
        website: 'https://boweryfarming.com/',
        contact: 'See website "Contact" page.',
        ratedPower: 'Benchmark range: ~6–18 kWh/kg (no public Bowery EUI).',
        efficiency: 'Substantially lower water use vs. field.',
        costNotes: 'Energy is often the dominant OpEx in CEA—lighting & HVAC.',
        sources: '(ScienceDirect, Accio)',
      },
      {
        name: 'Plenty',
        location: 'South San Francisco, CA, USA',
        quality: 'Proven',
        description: 'Vertical farming company that produces kale, arugula, mixed spices, and exotic herbs for retailers.',
        website: 'https://www.plenty.ag/about-us/',
        contact: '1-650-735-3737 or see "Contact Us" page.',
        ratedPower: 'New VA campus targeted up to ~20 million lb/yr output (all crops).',
        efficiency: 'High automation; crop set expanding.',
        sources: '(The Business Download)',
      },
      {
        name: 'InFarm',
        location: 'Berlin, Germany',
        quality: 'Proven',
        description: 'Vertical farming company providing produce in Europe from its Berlin headquarters.',
        website: 'https://www.infarm.com/',
        contact: 'See website "Contact" page.',
        ratedPower: 'Use industry ~6–18 kWh/kg planning range (site dependent).',
        efficiency: '~5 L/kg claim cited in feature (context: older reporting).',
        costNotes: 'Recent restructuring; check current footprint.',
        sources: '(ScienceDirect, WIRED)',
      },
      {
        name: 'Gotham Greens',
        location: 'New York and Chicago, USA',
        quality: 'Proven',
        description: 'Hydroponic vertical farming company, primarily in greenhouses.',
        website: 'https://www.gothamgreens.com/',
        contact: 'See website "Contact" page.',
        ratedPower: 'Typically lower EUI than windowless vertical farms (sunlight offset).',
        efficiency: '<3 gal/lb → <25 L/kg water. 20–30× field yield per area.',
        costNotes: 'Sun-lit CEA: lower energy, strong water-savings.',
        sources: '(Gotham Greens, bondstreet.com)',
      },
      {
        name: 'Iron Ox',
        location: 'California-based, USA',
        quality: 'Proven',
        description: 'Operates a fully autonomous indoor farm, using robots to plant and pick crops. Supplies Northern California and Central Texas.',
        website: 'https://ironox.com/',
        contact: 'See website "Contact Sales" page.',
        efficiency: 'Fully autonomous greenhouse modules; robotics & AI.',
        costNotes: 'Request site-specific metered kWh/kg before procurement.',
        sources: '(agritechtomorrow.com)',
      },
      {
        name: 'AgriCool',
        location: 'Paris, France',
        quality: 'Proven',
        description: 'Vertical farming company focused on container farms.',
        website: 'https://www.agricool.co',
        contact: 'See website "Contact" page.',
        costNotes: 'Year-round urban strawberry production; modular "Cooltainers." Berry crops generally more energy-intensive.',
        sources: '(Veolia Institute)',
      },
      {
        name: 'CropOne',
        location: 'Millis, MA, USA',
        quality: 'Proven',
        description: 'Uses data to collect insights on its vertical farming products and operations.',
        website: 'https://cropone.ag/',
        contact: 'See website "Investors" page.',
        ratedPower: 'Use ~6–18 kWh/kg lettuce benchmark pending site data.',
        efficiency: 'Operates large facilities; analytics-heavy ops.',
        sources: '(ScienceDirect)',
      },
      {
        name: 'Permaculture (National Agricultural Library)',
        location: 'USA',
        quality: 'Proven',
        description: 'Database and information on permaculture from the US National Agricultural Library.',
        website: 'https://www.nal.usda.gov/legacy/afsic/permaculture',
        contact: '(301)-504-5755 or see "Contact Us" page.',
        costNotes: 'Repository for practices; no facility KPIs.',
      },
    ],
  },
  {
    category: 'Geothermal HVAC (Ground & Air Source)',
    technologies: [
      {
        name: 'Samsung',
        location: 'Nationwide USA',
        productName: 'Heat Pump Dryer',
        quality: 'Proven',
        description: 'Air source heat pump dryer.',
        website: 'https://www.samsung.com/us/home-appliances/dryers/ventless/dve6800-4-0-cu--ft--24--heat-pump-dryer-with-smart-care-dv22n6800hw-a2/',
        contact: 'Nationwide business.',
        ratedPower: '4.0 cu ft',
        efficiency: 'Heat-pump drying (electric)',
        costNotes: 'Retail pricing varies',
        sources: '(product page)',
      },
      {
        name: 'TRANE™',
        location: 'Nationwide USA',
        productName: 'Geothermal Heat Pumps',
        quality: 'Proven',
        description: 'Geothermal HVAC systems that also provide hot water. Nationwide installer and maintenance network.',
        website: 'https://www.trane.com/residential/en/products/heat-pumps/',
        contact: 'Nationwide network.',
        ratedPower: 'Residential & light-comm. tonnages',
        efficiency: 'High COP/EER by model; DHW options',
        costNotes: 'Request quote',
        sources: '(catalog pages by model)',
      },
      {
        name: 'ClimateMaster™',
        location: 'Oklahoma City, OK, USA',
        productName: 'Commercial Geothermal Heat Pumps',
        quality: 'Proven',
        description: 'Geothermal heat pump that can also provide hot water as well as HVAC.',
        website: 'https://www.climatemaster.com/commercial/products',
        contact: '7300 S.W. 44th Street, Oklahoma City, OK 73179',
        ratedPower: 'Broad product lineup',
        efficiency: 'Model-specific EER/COP',
        costNotes: 'Request quote',
        sources: '(commercial product page)',
      },
    ],
  },
  {
    category: 'Mini-Split Heat Pumps',
    technologies: [
      {
        name: 'Pioneer',
        productName: 'WYS 9,000 BTU (single-zone)',
        quality: 'Proven',
        description: 'A highly efficient single-zone mini-split, ideal for spaces like bedrooms or small offices up to 350 sq ft. Est. cooling power ~0.38 kW (~$0.06/hr at $0.15/kWh).',
        website: 'https://www.pioneerminisplit.com/products/pioneer-9000-btu-230v-ductless-wys-energy-star-mini-split-air-conditioner-heat-pump-system-full-set',
        ratedPower: '9,000 BTU/h',
        efficiency: '24.0 SEER2',
        costNotes: '$988 (equipment only)',
        sources: 'Home Depot, Pioneer Mini Split',
      },
      {
        name: 'Mitsubishi Electric',
        productName: 'MSZ-FS12NA / MUZ-FS12NAH',
        quality: 'Proven',
        description: 'A premium, high-efficiency single-zone unit for spaces up to 550 sq ft, with excellent cold-climate performance. Est. cooling power ~0.52 kW (~$0.08/hr at $0.15/kWh).',
        website: 'https://www.build.com/mitsubishi-msz-fs12na-muz-fs12nah/s1972126',
        ratedPower: '13,600 BTU/h (cooling)',
        efficiency: '26.3 SEER2',
        costNotes: '$2,694 (equipment only)',
        sources: 'Build.com',
      },
      {
        name: 'Daikin',
        productName: 'Aurora 12,000 BTU (R-32)',
        quality: 'Proven',
        description: 'A single-zone unit using modern R-32 refrigerant, suitable for spaces up to 600 sq ft. Est. cooling power ~0.57 kW (~$0.09/hr at $0.15/kWh).',
        website: 'https://hvacdirect.com/12-000-btu-daikin-aurora-21-seer2-single-zone-wall-mount-mini-split-heat-pump-system-r32-230v-194698.html',
        ratedPower: '12,000 BTU/h',
        efficiency: '21.0 SEER2',
        costNotes: '$2,339 (equipment only)',
        sources: 'HVACDirect',
      },
      {
        name: 'MRCOOL',
        productName: 'DIY 5th-Gen 18,000 BTU',
        quality: 'Proven',
        description: 'A DIY-friendly single-zone unit for large spaces up to 800 sq ft, featuring pre-charged line sets for easy installation. Est. cooling power ~0.80 kW (~$0.12/hr at $0.15/kWh).',
        website: 'https://mrcooldirect.com/products/mrcool-diy%C2%AE-5th-generation-energy-star-18-000-btu-single-zone-mini-split-system-with-25ft-line-set-230v-model-diy-18-hp-wm-230d25-o',
        ratedPower: '18,000 BTU/h',
        efficiency: '22.5 SEER2',
        costNotes: '$2,909 (equipment only)',
        sources: 'Home Depot, MRCOOL Direct',
      }
    ]
  },
  {
    category: 'Carbon Sequestration and Fuels',
    technologies: [
      {
        name: 'Carbon Engineering',
        location: 'Squamish, B.C., Canada',
        productName: 'AIR TO FUELS™',
        quality: 'Emerging',
        description: 'Making a liquid fuel by sucking CO2 out of the atmosphere and combining it with hydrogen from water.',
        website: 'https://carbonengineering.com/',
        contact: 'See website "Contact Us" page.',
        ratedPower: 'Commercial-scale projects w/ partners',
        costNotes: 'Project finance (no public $/L)',
        efficiency: 'Long-lead EPC',
        sources: '(official site overview)',
      },
      {
        name: 'ALGAE PRODUCTION SYSTEMS',
        location: 'Houston, Texas, USA',
        quality: 'Proven',
        description: 'Algae production and distillation into oil and biomass.',
        website: 'http://www.algaeproductionsystems.com/equipment.html',
        contact: '1-832-515-9670',
        ratedPower: 'Skids & PBRs',
        costNotes: 'Request quote',
        efficiency: 'Biofuels feedstock',
        sources: '(equipment page)',
      },
      {
        name: 'U.S. Freedom BioFuels, LLC',
        location: 'Mosinee, WI, USA',
        quality: 'Proven',
        description: 'Biofuels from cooking fat or animal fats.',
        website: 'https://usfreedombiofuels.com/biodiesel-processors/',
        contact: '1-847-756-7600',
        ratedPower: 'Skids for WVO/animal fat',
        costNotes: 'Retail pricing per processor',
        efficiency: 'SMB scale',
        sources: '(product page)',
      },
      {
        name: 'GREEN CITY SOLUTIONS',
        location: 'Bestensee, Germany',
        quality: 'Emerging',
        description: 'Artificial tree benches (likely moss-based) for air purification/carbon sequestration.',
        website: 'https://greencitysolutions.de/en/benefits/',
        contact: 'info@mygcs.de or +49 33763 222144',
        efficiency: 'Air quality & CO₂ capture',
        costNotes: 'City procurement',
        sources: '(benefits page)',
      },
    ],
  },
  {
    category: 'Algae Bioreactors',
    technologies: [
      {
        name: 'Photon Systems Instruments',
        location: 'Drásov, Czech Republic',
        productName: 'Large-scale Photobioreactors',
        quality: 'Proven',
        description: 'Large-scale photobioreactors to create a controlled environment for upscaling photosynthetic microorganisms’ biomass production.',
        website: 'https://photo-bio-reactors.com/products/large-scale-pbrs/',
        contact: 'info(at)psi.cz or +420 511 440 012',
        ratedPower: 'Large reactors (industrial scale)',
        efficiency: 'For upscaling microalgae biomass',
        sources: '(Biomatrix)',
      },
    ],
  },
  {
    category: 'Renewable Housing Options',
    technologies: [
      {
        name: 'Hebel',
        location: 'San Antonio, Texas, USA',
        quality: 'Proven',
        description: 'Autoclaved Aerated Concrete (AAC) building materials.',
        website: 'https://www.hebel-usa.com/',
        contact: 'hebel-usa@hebel-usa.com or 210-402-3223',
        efficiency: 'High R-value per inch vs CMU; lightweight. Structural + insulation in one.',
        sources: '(vendor sites)',
      },
      {
        name: 'ACC WEST LLC',
        location: 'Phoenix, AZ, USA',
        quality: 'Proven',
        description: 'Autoclaved Aerated Concrete (AAC) building materials.',
        website: 'https://www.aacwestllc.com/about',
        contact: '928.716.1000 (Bob Steel)',
        efficiency: 'High R-value per inch vs CMU; lightweight. Structural + insulation in one.',
        sources: '(vendor sites)',
      },
      {
        name: 'AERCON AAC',
        location: 'Haines City, Florida, USA',
        quality: 'Proven',
        description: 'Autoclaved Aerated Concrete (AAC) building materials.',
        website: 'https://www.aerconaac.com/',
        contact: 'info@aerconaac.com or +1-(863)-422-6360',
        efficiency: 'High R-value per inch vs CMU; lightweight. Structural + insulation in one.',
        sources: '(vendor sites)',
      },
      {
        name: 'DDV LLC',
        location: 'Cheyenne, Wyoming, USA',
        quality: 'Proven',
        description: 'Metal buildings (website is metalbuildingsecrets.com)',
        website: 'www.metalbuildingsecrets.com',
        contact: '307-996-6302',
      },
      {
        name: 'CELL-CRETE',
        location: 'Monrovia, CA, USA',
        quality: 'Proven',
        description: 'Cellular concrete.',
        website: 'https://www.cell-crete.com/locations/',
        contact: 'info@cell-crete.com or 800-660-8062',
        efficiency: 'Lightweight fills, insulation',
        costNotes: 'Project-engineered',
        sources: '(locations page)',
      },
      {
        name: 'IsoHemp',
        location: 'Fernelmont, Belgium',
        quality: 'Proven',
        description: 'Hemp-blocks for natural building and masonry.',
        website: 'https://www.isohemp.com/en/hemp-blocks-naturally-efficient-masonry',
        contact: '+32 (0)81 39 00 13',
        efficiency: 'Vapor-open; moderate R; low embodied carbon. Structural w/ frames.',
        sources: '(product pages)',
      },
      {
        name: 'Just BioFiber',
        location: 'Calgary, Alberta, Canada',
        quality: 'Proven',
        description: 'Hempcrete blocks with a plastic frame to reinforce the structure and ease building/labor input.',
        website: 'https://justbiofiber.com/',
        contact: 'info@justbiofiber.com or 1-855-984-5427',
        efficiency: 'Vapor-open; moderate R; low embodied carbon. Structural w/ frames.',
        sources: '(product pages)',
      },
    ],
  },
  {
    category: 'Solar Tubes & Passive Windows',
    technologies: [
      {
        name: 'Solatube',
        location: 'Vista, CA, USA',
        productName: '290 DS',
        quality: 'Proven',
        description: 'Tubular skylights, including models with integrated solar-electric technology to power a smart NightLight.',
        website: 'https://solatube.com/residential/tubular-skylight/',
        contact: '(888) 765-2882',
        ratedPower: 'Light coverage area: approx 250-300 ft²',
        efficiency: 'Max tube length ~30 ft; U-value ~1.3 W/m²·K (~R-4.5)',
        costNotes: 'Dealer-installed; price varies by roof conditions, length of run, accessories.',
        sources: '(Solatube, SpecifiedBy)',
      },
      {
        name: 'VELUX',
        location: 'Fort Mill, SC, USA',
        productName: 'Sun Tunnels',
        quality: 'Proven',
        description: 'Flexible and Rigid Sun Tunnels (tubular skylights).',
        website: 'https://www.veluxusa.com/products/sun-tunnels',
        contact: 'See website "Contact Us" page.',
        ratedPower: 'Max install length: 20-40 ft by size',
        efficiency: 'Flexible and rigid models available',
        costNotes: 'Retail + installer quote. Pricing depends on size/roof type/flex vs rigid.',
        sources: '(Skylight.com)',
      },
      {
        name: 'Raven Windows',
        location: 'Denver, CO, USA',
        quality: 'Emerging',
        description: 'Auto-transitioning windows.',
        website: 'https://www.ravenwindow.com/residential',
        contact: 'admin@ravenwindow.com',
      },
      {
        name: 'ZOLA',
        location: 'USA',
        productName: 'Passive House Windows',
        quality: 'Proven',
        description: 'Passive House windows in aluminum, uPVC, and wood frames. High-performance windows with no drafts or condensation.',
        website: 'www.zolawindows.com',
        contact: '303-578-0001',
        ratedPower: 'R-Values up to ~R-11',
        efficiency: 'U-value ~0.78 W/m²·K (~R-7.2) for some fixed models',
        costNotes: 'Premium pricing; quote required for size/configuration.',
        sources: '(zolawindows.com, phius.org)',
      },
      {
        name: '3M',
        location: 'Nationwide USA',
        productName: 'Sun Control / Thinsulate Window Films',
        quality: 'Proven',
        description: 'Energy Star rated Mirror Film to reflect heat and UV, save energy, and prevent furniture fading.',
        website: 'https://www.3m.com/3M/en_US/building-window-solutions-us/solutions/energy/',
        contact: 'Nationwide/International company.',
        efficiency: 'Up to 97% IR rejection; Blocks up to ~99.9% UV rays',
        costNotes: 'Film + install cost; varies widely by glass area and project.',
        sources: '(3M Multimedia)',
      },
    ],
  },
  {
    category: 'Water Production',
    technologies: [
      {
        name: 'AWG Contracting',
        location: 'San Antonio, Texas, USA',
        quality: 'Proven',
        description: 'A non-profit company (under the Moses West Foundation) that provides clean drinking water to local communities.',
        website: 'https://awgcontractingus.com/awg-about-charity/',
        contact: 'info@awgcontractingus.com',
      },
      {
        name: 'Source',
        location: 'Scottsdale, AZ, USA',
        productName: 'Hydropanel',
        quality: 'Proven',
        description: 'Hydro Panels that use solar energy to produce water for residential and commercial properties.',
        website: 'https://www.source.co/residential/',
        contact: '+1-855-796-9283 or see "Contact Us" page.',
        ratedPower: '~2.5–3.5+ L/day per panel (climate-dependent)',
        efficiency: 'Solar-powered; optional pump',
        costNotes: '1–2 panels per home tap typical',
        sources: '(SOURCE)',
      },
      {
        name: 'Biomatrix Water',
        location: 'Forres, Scotland',
        quality: 'Proven',
        description: 'Greenhouse water purification.',
        website: 'https://www.biomatrixwater.com/',
        contact: 'solutions@biomatrixwater.com or +44 (0)1309 678 100',
        ratedPower: 'Water quality restoration (nutrients/solids/metals reduction)',
        costNotes: 'City/river retrofits',
        sources: '(Biomatrix)',
      },
      {
        name: 'Water Gen',
        location: 'Charlotte, NC, USA',
        productName: 'GEN-L / GENNY',
        quality: 'Proven',
        description: 'Atmospheric water generators for homes, offices, schools, and large establishments.',
        website: 'https://us.watergen.com/',
        contact: '+1-888-492-8370 or see "Contact Us" page.',
        ratedPower: 'GEN-L: Up to 6,000 L/day. GENNY: Up to 20-30 L/day.',
        efficiency: 'GEN-L: ~350 Wh/L. GENNY: ~400 Wh/L.',
        costNotes: 'GEN-L is 3-phase, GENNY is plug-in.',
        sources: '(Watergen)',
      },
      {
        name: 'Tsunami Products',
        location: 'Liberty Lake, WA, USA',
        productName: 'T50 / T500',
        quality: 'Proven',
        description: 'Atmospheric water generators made in the USA for homes, offices, and large establishments.',
        website: 'https://www.tsunamiproducts.com/products',
        contact: 'info@tsunamiproducts.com or +1-800-680-4039',
        ratedPower: 'T50: ~57 L/day. T500: up to ~454 L/day.',
        efficiency: 'T50: Est. energy ~$0.16/gal @ $0.10/kWh',
        costNotes: 'Made in USA, solar option available.',
        sources: '(prepsos.com, Environmental Expert)',
      },
      {
        name: 'VENA',
        location: 'Los Angeles, CA, USA',
        quality: 'Experimental',
        description: 'Large-scale, passive atmospheric water generator for agriculture and water scarcity.',
        website: 'http://www.venawater.com/solution',
        contact: 'See website "Contact Us" page.',
        costNotes: 'Request quote',
        sources: '(Autodesk)',
      },
    ],
  },
  {
    category: 'HHO Generators',
    technologies: [
      {
        name: 'Better Fuel Technology',
        location: 'Ottawa, Ontario, Canada',
        quality: 'Experimental',
        description: 'HHO generators.',
        website: 'https://www.hho-1.com/',
        contact: 'info@hho-1.com or 1-613-866-9789',
      },
      {
        name: 'Green Fuel H2O',
        location: 'Orem, Utah, USA',
        quality: 'Experimental',
        description: 'HHO generators.',
        website: 'https://www.greenfuelh2o.com/shop/',
        contact: 'info@greenfuelh2o.com',
      },
      {
        name: 'Hydrox Systems',
        location: 'Argeliers, France',
        quality: 'Experimental',
        description: 'HHO generators.',
        website: 'https://www.hydroxsystems.com/contact-us/',
        contact: 'france@hydroxsystems.com or +33 633 342267',
      },
    ],
  },
  {
    category: 'Next-Gen: Sodium-Ion Batteries',
    technologies: [
      {
        name: 'Altris AB',
        location: 'Uppsala, Sweden',
        quality: 'Emerging',
        description: 'A leading developer of cathode materials for sodium-ion batteries.',
        website: 'www.altris.se',
        contact: 'hi@altris.se or info@altris.se',
        efficiency: '~160 Wh/kg (validated)',
        costNotes: 'Market signals ~$80–$90/kWh (2024 avg.); long-run potential $40–$50/kWh',
        sources: '(altris.se, IDTechEx)',
      },
      {
        name: 'Tiamat',
        location: 'Amiens, France',
        quality: 'Emerging',
        description: 'A company spinning out of French research labs to commercialize sodium-ion cells for automotive and storage applications.',
        website: 'www.tiamat-energy.com',
        contact: 'contact@tiamat-energy.com',
        efficiency: '~100–120 Wh/kg (high-power cells); >5,000 cycles to ~80%; fast-charge',
        costNotes: 'Company emphasizes low cost vs. LTO; no list price.',
        sources: '(en.wikipedia.org, worldmaterialsforum.com)',
      },
      {
        name: 'Faradion',
        location: 'Sheffield, UK',
        quality: 'Emerging',
        description: 'A pioneer in sodium-ion technology, now owned by Reliance, but with its core R&D remaining in the UK.',
        website: 'www.faradion.co.uk',
        contact: 'info@faradion.co.uk',
        efficiency: '>190 Wh/kg (proto pouch; scaling to 32 Ah)',
        costNotes: 'Long-term potential $40–$80/kWh',
        sources: '(Faradion, Apricum Group)',
      },
      {
        name: 'Litona',
        location: 'Karlsruhe, Germany',
        quality: 'Emerging',
        description: 'A German startup focused on high-quality, locally sourced sodium-ion battery cells.',
        website: 'www.litona.de',
        contact: 'contact@litona.de',
        efficiency: 'Material spec: 150 mAh/g, ~3.45 V vs Na/Na⁺ (cathode)',
        costNotes: 'Cell $/kWh not posted; use Na-ion market ranges.',
        sources: '(litona-batteries.de, IDTechEx)',
      },
    ],
  },
  {
    category: 'Next-Gen: Enhanced Geothermal Systems (EGS)',
    technologies: [
      {
        name: 'Fervo Energy',
        location: 'USA',
        productName: 'Cape Station',
        quality: 'Emerging',
        description: 'A US-based company that uses innovations from the oil and gas industry (like horizontal drilling) to make EGS commercially viable. They have active projects in Utah and Nevada.',
        website: 'www.fervoenergy.com',
        contact: 'info@fervoenergy.com',
        ratedPower: '500 MW multi-phase; 100 MW online 2026',
        costNotes: 'FOAK EGS LCOE estimates ~$200/MWh today; modeled floor cases ~$87/MWh',
        efficiency: 'Horizontal drilling, fiber-optic monitoring; well costs fell from $9.4M → $4.8M',
        sources: '(Fervo Energy, Carnegie Endowment, POWER Magazine)',
      },
      {
        name: 'Eavor',
        location: 'Canada',
        productName: 'Eavor-Loop™',
        quality: 'Emerging',
        description: 'A Canadian company known for its unique "Eavor-Loop" technology, a closed-loop system that acts like a massive underground radiator.',
        website: 'www.eavor.com',
        contact: 'info@eavor.com',
        ratedPower: 'Geretsried (DE) project: target ~8.2 MW electric (plus 60 MWth heat)',
        costNotes: 'LCOE target ~$75/MWh by ~2029–30',
        efficiency: 'Closed-loop radiator-style system (no fracking/permeability dependence)',
        sources: '(Eavor)',
      },
      {
        name: 'Quaise Energy',
        location: 'USA',
        quality: 'Experimental',
        description: 'A startup from MIT (based in Massachusetts) developing a novel drilling technology using millimeter waves to drill deeper than ever before, unlocking geothermal energy anywhere.',
        website: 'www.quaise.energy',
        contact: 'info@quaise.energy',
        ratedPower: 'Field milestone: 100 m drilled with mm-wave',
        costNotes: 'Internal LCOE modeling tool aligned with Lazard geothermal ranges',
        efficiency: 'Aims to drill deeper/hotter using millimeter-wave gyrotrons',
        sources: '(Quaise Energy)',
      },
      {
        name: 'AltaRock Energy',
        location: 'Seattle, USA',
        quality: 'Emerging',
        description: 'A leader in EGS technology and development, with significant experience in projects in the Western US.',
        website: 'www.altarockenergy.com',
        contact: 'info@altarockenergy.com',
        costNotes: 'Superhot-rock (SHR) study indicates potential < $0.05/kWh LCOE',
        efficiency: 'SHR pathway seeks step-change in cost vs conventional EGS',
        sources: '(Renewables Now, Factor This™)',
      },
    ],
  },
  {
    category: 'Next-Gen: Direct Air Capture (DAC)',
    technologies: [
      {
        name: 'Heirloom',
        location: 'USA',
        quality: 'Emerging',
        description: 'A California-based company that uses limestone to pull CO2 from the air. They are building America\'s first commercial DAC facilities in California and Louisiana.',
        website: 'www.heirloomcarbon.com',
        contact: 'Use dedicated contact form.',
        ratedPower: 'Tracy, CA plant: up to ~1,000 tCO₂/yr capture',
        costNotes: 'Current DAC market prices typically $500–$1,000 per tCO₂',
        efficiency: 'Limestone (CaCO₃) looping with mineralization/storage pathways',
        sources: '(heirloomcarbon.com, The Nature Conservancy, Canary Media)',
      },
      {
        name: 'CarbonCapture Inc.',
        location: 'USA',
        productName: 'Leo Modules',
        quality: 'Emerging',
        description: 'A company based in Wyoming, developing a modular DAC system designed for mass production and deployment.',
        website: 'www.carboncapture.com',
        contact: 'Use contact form; press@carboncapture.com for press.',
        ratedPower: '“Leo” modular units ≥ 500 tCO₂/yr per container; Project Bison target 5 Mt/yr by 2030',
        costNotes: 'Firm pricing is site/partner-specific',
        efficiency: 'Solid-sorbent modular DAC; designed for mass production',
        sources: '(carboncapture.com)',
      },
    ],
  },
  {
    category: 'Next-Gen: Tidal and Wave Energy',
    technologies: [
      {
        name: 'ORPC',
        location: 'Portland, Maine, USA',
        productName: 'RivGen®',
        quality: 'Emerging',
        description: 'A US company that has deployed its river and tidal power systems in Maine, Alaska, and Canada.',
        website: 'www.orpc.co',
        contact: '(207) 772-2207 or use Contact Page',
        ratedPower: 'Commercial RivGen at Igiugig (AK) ~35 kW per unit',
        costNotes: 'Remote sites offset $0.21–$0.40+/kWh diesel',
        efficiency: 'Suits remote/diesel-reliant communities; baseload-like river current power',
        sources: '(en.wikipedia.org, MHKDR, ORPC)',
      },
      {
        name: 'Orbital Marine Power',
        location: 'Scotland, UK',
        productName: 'O2 Tidal Turbine',
        quality: 'Emerging',
        description: 'A leading developer of floating tidal turbines, with its O2 turbine operating in the waters off Scotland.',
        website: 'www.orbitalmarine.com',
        contact: 'webenquiries@orbitalmarine.com',
        ratedPower: '2.0 MW floating turbine',
        costNotes: 'Target LCOE < £200/MWh for first O2',
        efficiency: 'World’s largest tidal stream device in operation',
        sources: '(scottish-enterprise.com, Orbital Marine)',
      },
      {
        name: 'Sinn Power',
        location: 'Gauting, Germany',
        productName: 'WEC Platform',
        quality: 'Emerging',
        description: 'A German company developing modular, hybrid wave energy converter platforms that can also integrate wind and solar.',
        website: 'www.sinnpower.com',
        contact: 'Use contact form.',
        ratedPower: 'Module configurations 24 kW and 36 kW',
        costNotes: 'No public LCOE; platform aims to hybridize with PV + wind',
        efficiency: 'Modular floating platform—wave, solar, and wind co-location',
        sources: '(Engineering.com, Wave Energy Index)',
      },
      {
        name: 'CorPower Ocean',
        location: 'Stockholm, Sweden',
        productName: 'C4/C5 Wave Energy Converter',
        quality: 'Emerging',
        description: 'A Swedish company that has developed wave energy converters inspired by the pumping principle of the human heart.',
        website: 'www.corpowerocean.com',
        contact: 'info@corpowerocean.com',
        ratedPower: '~300 kW (C4 device; rated)',
        costNotes: 'Industry tracking toward €100–€200/MWh at early-commercial scale',
        efficiency: 'Point-absorber “heart-inspired” PTO; arrays under demonstration',
        sources: '(openei.org, ren21.net, CorPower Ocean)',
      },
    ],
  },
  {
    category: 'Next-Gen: Green Hydrogen Production',
    technologies: [
      {
        name: 'HySynergy (Everfuel)',
        location: 'Denmark',
        quality: 'Emerging',
        description: 'A major project in Denmark that is already producing green hydrogen.',
        website: 'www.everfuel.com',
        contact: 'sayhy@everfuel.com',
        ratedPower: '20 MW (Phase 1) with scale-up strategy toward 1 GW',
        efficiency: '~8,000 kg/day at Fredericia (Phase 1)',
        costNotes: 'Levelized cost depends on power price; DK wind/solar PPA driven.',
        sources: '(mb.cision.com, Everfuel.com)',
      },
      {
        name: 'Andalusian Green Hydrogen Valley (Cepsa/Moeve)',
        location: 'Spain',
        quality: 'Emerging',
        description: 'A large-scale project led by the company Moeve (formerly Cepsa).',
        website: 'https://www.cepsa.com/en/our-commitment-to-sustainability/positive-motion/green-hydrogen',
        contact: 'Use main Moeve contact page.',
        ratedPower: '2 GW total electrolysis (two hubs)',
        efficiency: 'Up to ~300,000 t/yr green H₂ when fully built',
        costNotes: '€3B+ project; phased FIDs.',
        sources: '(Moeve Global)',
      },
      {
        name: 'Project Anker (Friesen Elektra & CIP)',
        location: 'Germany',
        quality: 'Emerging',
        description: 'A planned 800MW green hydrogen production facility by Copenhagen Infrastructure Partners (CIP).',
        website: 'https://cip.com/',
        contact: 'media@cip.com or orsk@cip.com',
        ratedPower: '400 MW initial, expandable to 800 MW',
        efficiency: '~80,000 t/yr green H₂ (proj.)',
        costNotes: 'Grid-connected renewables (on/offshore wind + solar).',
        sources: '(GlobeNewswire, Renewable Energy Magazine, Enerdata)',
      },
    ],
  },
];
