
import React from 'react';
import type { AnalysisContent, FormData } from '../types';

interface PrintablePermittingPackProps {
  formData: FormData;
  analysisContent: AnalysisContent;
}

const PrintablePermittingPack: React.FC<PrintablePermittingPackProps> = ({ formData, analysisContent }) => {
  if (!analysisContent || !analysisContent.text) {
    return (
      <div className="printable-pack">
        <h1>Permitting & Incentives Pack</h1>
        <p>No data available to print.</p>
      </div>
    );
  }

  const { text, sources } = analysisContent;

  return (
    <div className="printable-pack" style={{ fontFamily: 'sans-serif', color: '#333', padding: '2rem' }}>
      <header style={{ borderBottom: '2px solid #22c55e', paddingBottom: '1rem', marginBottom: '2rem' }}>
        <h1 style={{ fontSize: '2.5rem', color: '#166534', margin: 0 }}>Permitting & Incentives Pack</h1>
        <p style={{ fontSize: '1.1rem', margin: '0.5rem 0 0' }}><strong>For:</strong> {formData.location}</p>
        <p style={{ fontSize: '1.1rem', margin: '0.25rem 0 0' }}><strong>Date:</strong> {new Date().toLocaleDateString()}</p>
      </header>
      
      <div dangerouslySetInnerHTML={{ __html: text.replace(/\n/g, '<br />') }} />

      {sources && sources.length > 0 && (
        <section style={{ marginTop: '3rem', paddingTop: '1.5rem', borderTop: '1px solid #ccc' }}>
          <h2 style={{ fontSize: '1.8rem', color: '#166534', borderBottom: '1px solid #ccc', paddingBottom: '0.5rem' }}>Sources Consulted</h2>
          <ul style={{ listStyleType: 'decimal', paddingLeft: '20px' }}>
            {sources.map((source, index) => {
              const sourceData = source.web || source.maps;
              return (
                <li key={index} style={{ marginBottom: '0.5rem' }}>
                  <a href={sourceData?.uri} style={{ color: '#15803d', textDecoration: 'none' }}>
                    {sourceData?.title}
                  </a>
                  <p style={{ margin: '0.25rem 0 0', fontSize: '0.8rem', color: '#555' }}>{sourceData?.uri}</p>
                </li>
              );
            })}
          </ul>
        </section>
      )}

      <footer style={{ marginTop: '3rem', paddingTop: '1rem', borderTop: '2px solid #22c55e', textAlign: 'center', fontSize: '0.9rem', color: '#777' }}>
        <p>Report generated by the Green Energy Candidate Analyzer.</p>
      </footer>
    </div>
  );
};

export default PrintablePermittingPack;
