
import React from 'react';
import type { FormData, AnalysisResults } from '../types';
import { UserRole } from '../types';
import PrintableEnergyComparisonChart from './charts/PrintableEnergyComparisonChart';
import PrintableCostSavingsChart from './charts/PrintableCostSavingsChart';

interface PrintableReportProps {
  formData: FormData;
  analysisResults: AnalysisResults;
}

const PrintableReport: React.FC<PrintableReportProps> = ({ formData, analysisResults }) => {

  const parseFinancials = (text: string) => {
    const costMatch = text.match(/Estimated System Cost:\s*\$\[([\d,.]+)\]/);
    const savingsMatch = text.match(/Estimated Annual Electricity Savings\/Revenue:\s*\$\[([\d,.]+)\]/);
    const paybackMatch = text.match(/Simple Payback Period:\s*\[([\d.]+)\]/);

    const systemCost = costMatch ? parseFloat(costMatch[1].replace(/,/g, '')) : 0;
    const annualSavings = savingsMatch ? parseFloat(savingsMatch[1].replace(/,/g, '')) : 0;
    const paybackPeriod = paybackMatch ? parseFloat(paybackMatch[1]) : 0;

    return { systemCost, annualSavings, paybackPeriod };
  };

  const financials = parseFinancials(analysisResults.finalReport.text);

  return (
    <div className="printable-report">
      <header>
        <h1>Green Energy Analysis Report</h1>
        <p><strong>Role:</strong> {formData.role}</p>
        <p><strong>Location:</strong> {formData.location}</p>
      </header>

      <section>
        <h2>Executive Summary</h2>
        <p>{analysisResults.summary.text}</p>
      </section>

      {formData.role !== UserRole.SALES ? (
        <>
            <section>
                <h2>Financial & Environmental Impact</h2>
                <pre>{analysisResults.finalReport.text}</pre>
                <PrintableCostSavingsChart {...financials} />
            </section>

            <section>
                <h2>Energy Potential Analysis</h2>
                <PrintableEnergyComparisonChart 
                    currentAnnualUsage={parseFloat(formData.electricityUsage) * 12}
                    solarProductionText={analysisResults.solar.text}
                    windProductionText={analysisResults.wind.text}
                    hydroProductionText={analysisResults.hydro.text}
                />
            </section>
            
            <section>
                <h2>Detailed Analysis</h2>
                <h3>Energy Audit</h3>
                <pre>{analysisResults.energyAudit.text}</pre>
                
                <h3>Solar Potential</h3>
                <pre>{analysisResults.solar.text}</pre>
                
                <h3>Wind Potential</h3>
                <pre>{analysisResults.wind.text}</pre>

                <h3>Hydropower Potential</h3>
                <pre>{analysisResults.hydro.text}</pre>
                
                <h3>Battery Storage</h3>
                <pre>{analysisResults.battery.text}</pre>
            </section>
        </>
      ) : (
        <>
            <section>
                <h2>Sales & Marketing Playbook</h2>
                <pre>{analysisResults.salesSummary.text}</pre>
            </section>
        </>
      )}

      <footer>
        <p>Report generated by Green Energy Analyzer</p>
      </footer>
    </div>
  );
};

export default PrintableReport;
